% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Aug-2021 21:43:49
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('task2.mat');

d = [1 5 30];

n = 30;

r = saveVarsMat.r; % <1x15001 double> too many elements

t = saveVarsMat.t; % <1x15001 double> too many elements

y = saveVarsMat.y; % <15001x1 double> too many elements

clear saveVarsMat;
