% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Sep-2020 07:41:08
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('fourier_synthesis.mat');

X_0 = 0.5;

X_1 = saveVarsMat.X_1; % <1x9425 double> too many elements

X_2 = saveVarsMat.X_2; % <1x9425 double> too many elements

X_X = saveVarsMat.X_X; % <1x9425 double> too many elements

coeff = 59;

n = 28;

sign = 1;

t = saveVarsMat.t; % <1x9425 double> too many elements

clear saveVarsMat;
