% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Aug-2021 21:23:08
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('code.mat');

d = [1 5 30];

d1 = [1 5 30 0];

n = [0 0 30];

n1 = [0 0 0 30];

v = [0 10 0 10];

x = [];

y = saveVarsMat.y; % <5001x1 double> too many elements

z = saveVarsMat.z; % <1x5001 double> too many elements

clear saveVarsMat;
